# -------------------
# 1. SECRET MONGO
# -------------------
apiVersion: v1
kind: Secret
metadata:
  name: mongo
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==

---
# -------------------
# 2. CONFIGMAP APPLICATION
# -------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: application
data:
  MONGO_HOST: mongo
  MONGO_PORT: "27017"
  BG_COLOR: teal
  FAIL_FLAG: "false"
---
# -------------------
# 3. SERVICE MONGO
# -------------------
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

---
# -------------------
# 4. STATEFULSET MONGO
# -------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.2"
              memory: "128Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: MONGO_INITDB_ROOT_PASSWORD

---
# -------------------
# 5. DEPLOYMENT APPLICATION
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: cesarbuitrago/cbuitrago_application:latest
          ports:
            - containerPort: 5000

          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
            requests:
              cpu: "0.2"
              memory: "64Mi"

          envFrom:
            - configMapRef:
                name: application

          readinessProbe:
            httpGet:
              path: /healthx
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mongo 27017; do echo waiting for mongo; sleep 2; done;"
            ]

---
# -------------------
# 6. SERVICE APPLICATION
# -------------------
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: application

---
# -------------------
# 7. INGRESS
# -------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
    - host: cbuitrago.application.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: application
                port:
                  number: 80
